apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: k2m30/js_server:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_root_username
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_root_password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql_db_name
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql_host
            - name: MYSQL_PORT
              value: '3306'
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
#  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
#      nodePort: 30000
