#cloud-config

bootcmd:
  - echo 192.168.0.1 gw.homedns.xyz >> /etc/hosts
runcmd:
  - [ ls, -l, / ]
  - [ sh, -xc, "echo $(date) ': hello world!'" ]
ssh_pwauth: true
disable_root: false
chpasswd:
  list: |
    root:password
  expire: false
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, sudoers
    home: /home/ubuntu
    plain_text_passwd: ubuntu
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVOodsAOHJx/WZt2yWGbyGxMvWJa+z7wB9ITQGLtxTieIwA1vzc3Mzhwcqjn1s7XPXVsvb0WUGOtB9dBzmADn+aOpLxnGHVOzZOD5lN8rmeqVCL25y08ma4u9jznYYbOZEJxuvm9SNr44q+i0a1LMfZTffzZPLWw1cXCXUrCiY1SQ8gtJfULe/q3WZqhNOFtP2oqT5vz6WQqtqrS5Os99obDDzlt0VxvTcNKmgYQ75U8Y8qs3r44yF2tbWUB/Kx6411iytYQmUMA1YyI4A4IsCHrUyjNHrpxvcJvg6KeFssEmSSGEB93ytuxEjKD6D6JJWax/G3ddzBNT0Z2UxsHHz mikhail.chuprynski@gmail.com
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXv6+Nje8V/6ruh8Vsz8Orvy6GQu4p0X4I09mXzj8LDXKG54lIIUTtVlTRKhzG366/uJAP5LBpbhDcpilompZgpzIfTvVEXSU0aH0pTz/zuciu07sY6YYY++5ZEzPbrmCqTRZB9zd4GovWZEnYTBcS/a4JKSTzCfGOiLMbdvUnbLC/7USMe9Ev0s93Sla7n52E9EY3vPOxLS7nGfWCPp4XI2X7Y6lY3PGxdQasb0e0ediJM9IM+EdCJj72lnf062lLBYA/DV5Yb7C7tigznDcTie4/pdPM+i5xJF3y6aSBAtgbtU8mTKTpd/9TLyTQZuFpjyy3TMD4TFCctXTAsfpd ubuntu@dave
final_message: "The system is finally up, after $UPTIME seconds"