- hosts: nodes
  become: yes
  tasks:
    - name: disable firewall service
      ufw:
        state: disabled

    - name: Disable swap
      shell: swapoff -a

    - name: Disable swap in fstab
      lineinfile:
        path: /etc/fstab
        regexp: 'swap'
        state: absent

    - name: Update sysctl settings for Kubernetes networking IPv6
      sysctl:
        sysctl_file: /etc/sysctl.d/kubernetes.conf
        name: net.bridge.bridge-nf-call-ip6tables
        value: "1"
        state: present

    - name: Update sysctl settings for Kubernetes networking IPv4
      sysctl:
        sysctl_file: /etc/sysctl.d/kubernetes.conf
        name: net.bridge.bridge-nf-call-iptables
        value: "1"
        state: present

    - name: Install initial packages
      apt:
        package:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add an Docker signing key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add an Kubernetes signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Add Kubernetes repo
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install Docker and Kubernetes
      apt:
        update_cache: yes
        package:
          - docker-ce=5:19.03.10~3-0~ubuntu-focal
          - containerd.io
          - kubeadm=1.18.5-00
          - kubelet=1.18.5-00
        autoclean: yes
        autoremove: yes

- hosts: kube_masters
  become: yes
  tasks:
    - name: Install kubectl
      apt:
        package: kubectl=1.18.5-00
        autoclean: yes
        autoremove: yes

    - name: Init kubeadm
      shell: kubeadm init --apiserver-advertise-address={{inventory_hostname}} --pod-network-cidr=192.168.0.0/16  --ignore-preflight-errors=all

    - name: Deploy Calico
      shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml

    - name: Creates directory
      file:
        path: /home/user/.kube/
        state: directory
        owner: user

    - name: Copy admin.conf to user's kube config
      copy:
        remote_src: yes
        src: /etc/kubernetes/admin.conf
        dest: /home/user/.kube/config
        owner: user

    - name: Generate join command
      shell: kubeadm token create --print-join-command
      register: join_command
      check_mode: no

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
      check_mode: no
      become: no

###############################################################################
- hosts: kube_workers
  become: yes
  tasks:
    - name: Copy the join command to server location
      copy:
        src: join-command
        dest: /tmp/join-command.sh
        mode: 0755

    - name: Join the node to cluster
      command: sh /tmp/join-command.sh

    - name: Remove join-command file locally
      local_action: file path=./join-command state=absent
      check_mode: no
      become: no
